INSERT INTO TBL_STUDENT(ID, AGE, FIRST_NAME, GENDER, LAST_NAME, MIDDLE_NAME) VALUES (1, 27, 'VALENTIN',  'M', 'ALBERTO', 'IDUSORA');

INSERT INTO TBL_STUDENT(ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, GENDER, AGE) VALUES (2, 'JOHN LESTER', 'BANASIHAN', 'IBEK', 'M', 27);

SELECT * FROM TBL_STUDENT; 